version: 2.1
#updates
orbs:
  aws-cli: circleci/aws-cli@3.1.1
  aws-ecr: circleci/aws-ecr@8.1.3
  node: circleci/node@4.7
  discord: antonioned/discord@0.1.0

jobs:
  build-test-deploy-api-svc:
    working_directory: ~/circle-demo/
    docker:
      - image: cimg/node:20.13
    steps:
      - run: touch ~/circle-demo/tevaapi/.npmrc
      - run: >-
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/circle-demo/tevaapi/.npmrc
      - aws-ecr/build-and-push-image:
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./tevaapi/
          push-image: true
          repo: $AWS_ECR_API_SVC_REPO_NAME
          setup-remote-docker: true
          dockerfile: Dockerfile
          tag: $AWS_REGION
          create-repo: true
      - run: >-
          aws ecs update-service --force-new-deployment --service $AWS_ECS_API_SVC_SERVICE_NAME --cluster $AWS_ECS_SHR_CLUSTER_NAME
      - discord/status:
          webhook: $DISCORD_ALERTS_WEBHOOK_URL


workflows:
  deployment:
    jobs:
      - build-test-deploy-api-svc:
          filters:
            branches:
              only:
                - main
          name: Build, Test & Deploy to Development
          context: aws-backend-dev
